#!/bin/bash
revert() {
  rm /tmp/*screen*.png
  xset dpms 0 0 0
}
trap revert HUP INT TERM
xset +dpms dpms 0 0 5
maim "/tmp/locking_screen.png"
convert -blur 0x24 /tmp/locking_screen.png /tmp/screen_blur.png
convert -composite /tmp/screen_blur.png ~/Изображения/123.png -gravity South -geometry -20x1200 /tmp/screen.png
i3lock -i /tmp/screen.png	
revert
